#!/bin/bash
#AL MANCO UN PARÀMETRE

#EL FACTORIAL DE 1 ES 1
#EL FACTORIAL ÉS PER EXEMPLE 3!=3X2X1=6
#EL FACTORIAL DE 10!=19X9X8X7X6X5X4X3X2X1

FACTORIAL=1

while [ ${#} -gt 0 ]; do
    
    shift

done
echo "EL FACTORIAL DE ${1} VAL ${FACTORIAL}"